trigger:
  branches:
    include:
      - feature/*
      - fix/*

variables:
  ENV: dev

stages:
  - stage: CI
    jobs:
      - job: Build
        steps:
          - checkout: self
          - script: mvn clean install

          - script: |
              docker build -t app:$(Build.BuildId) .
              docker push app:$(Build.BuildId)

          - script: trivy image app:$(Build.BuildId)

  - stage: Deploy_Dev
    dependsOn: CI
    jobs:
      - deployment: DevDeploy
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    helm upgrade --install app ./helm \
                      --namespace dev \
                      --set image.tag=$(Build.BuildId)