trigger:
  branches:
    include:
      - post-prod

stages:
  - stage: SRE_Approval
    jobs:
      - job: Approval
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              instructions: "SRE Approval Required for DR"

  - stage: Deploy_DR
    dependsOn: SRE_Approval
    jobs:
      - deployment: DRDeploy
        environment: dr
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    helm upgrade --install app ./helm \
                      --namespace dr \
                      --set image.tag=$(Build.BuildId)
