trigger:
  branches:
    include:
      - hotfix/*

stages:
  - stage: Approval
    jobs:
      - job: FastApproval
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              timeoutInMinutes: 120
              instructions: "Approve Hotfix within 2 hours"

  - stage: Deploy_Hotfix
    dependsOn: Approval
    jobs:
      - deployment: HotfixDeploy
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    helm upgrade --install app ./helm \
                      --namespace prod \
                      --set image.tag=$(Build.BuildId)