trigger: none

pr:
  branches:
    include:
      - "*"

stages:
  - stage: Cleanup
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: DeleteNamespace
        steps:
          - script: |
              kubectl delete namespace pr-$(System.PullRequest.PullRequestId) || true