trigger: none

pr:
  branches:
    include:
      - develop
      - main

variables:
  IMAGE_NAME: streamvault
  TAG: pr-$(Build.BuildId)

stages:
  - stage: Build_Test
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - script: mvn clean install
            displayName: Build & Unit Test

          - script: |
              docker build -t $(IMAGE_NAME):$(TAG) .
            displayName: Build Docker Image

          - script: |
              trivy fs .
            displayName: Trivy FS Scan

  - stage: Preview_Deploy
    jobs:
      - deployment: DeployPreview
        environment: pr-env
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    kubectl create namespace pr-$(Build.BuildId) || true
                    helm upgrade --install app ./helm \
                      --namespace pr-$(Build.BuildId) \
                      --set image.tag=$(TAG)
